generated: '2026-07-11'
method: probed
source: live DNS/TLS/HTTP probes of apis.yml + OpenAPI hosts
hosts:
- host: www.listennotes.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 21 16:29:19 2026 GMT
  hsts: false
- host: listen-api.listennotes.com
  https: true
  tls_version: TLSv1.3
  cert_expires: Aug 21 16:29:19 2026 GMT
  hsts: false
domains:
- domain: listennotes.com
  dnssec: true
  caa:
  - 0 issuewild "pki.goog; cansignhttpexchanges=yes"
  - 0 issuewild "ssl.com"
  - 0 issue "amazon.com"
  - 0 issue "comodoca.com"
  - 0 issue "digicert.com; cansignhttpexchanges=yes"
  - 0 issue "letsencrypt.org"
  spf: true
  dmarc: true
  dmarc_policy: quarantine
